include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_single_quotes: true
    prefer_relative_imports: true
    directives_ordering: true

analyzer:
  errors:
    invalid_annotation_target: ignore